### ISSUE TITLE
User Story: Sending Messages in Channels

### ISSUE THREAD

**Issue by v2thegreat** [v2thegreat/SOEN-341-PRJKT#12]
As a user, I'd like to be able to send messages in Channels so that I can inform multiple groups at the same time

**Comment by jcdee01** [comment]
Priority: Medium
Risk: HIGH
Risk Associated: Technical Risk, Procedural, Productivity, Sudden Growth of Requirements

**Comment by kexuansong** [comment]
Acceptance test:
If the user tries to send messages in a channel, then the message appears on the message area of the channel and other users in the same channel can see it.

**Comment by jcdee01** [comment]
Breakdown:
Sending messages
---
- Create Message Backend (Kelvin) #33 
   -message functions
function: read user input
function: store user input to var
function: move all previous messagesup
function: store user name
function: write user input to channeland author's username

**Comment by jcdee01** [comment]
Risk Assesment
--
Story Point: 10
Priority: HIGH
Risk: HIGH
Risk Associated: Technical (Webstorm, React, Node.js), Procedural , Productivity Issues, Operational (siloing), Sudden Increase in Requirements

**Comment by jcdee01** [comment]
**Test Case: Send Messages**
Type: System(UI) Test
Description: Send Message in Valid Channel
Prerequisite: Premade Valid Channel
Test Priority: High
Step 1: Navigate to site
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Valid Email and Password  
(Input: “email:test@hotmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 3: Select Channel
(Input: click on the channel called “test”, Expected Output: Navigate to “test” channel view, Actual Output: Navigate to “test” channel view, Test Result: Pass)
Step 3: Message Channel
(Input: write “test” inside message box below, Expected Output: “test” appears in channel view on the left below previous messages, Actual Output: “test” appears in channel view on the left below previous messages, Test Result: Pass)
**FINAL RESULT: PASS**
