### ISSUE TITLE
User story: Joining channels

### ISSUE THREAD

**Issue by kexuansong** [v2thegreat/SOEN-341-PRJKT#13]
As a website user, I want to be able to join channels by channel ID, so I can join already established groups.

**Comment by jcdee01** [comment]
Risk Assesment
---
Story Point: 9
Priority: HIGH
Risk: HIGH
Risk Associated: Technical (Webstorm, React, Node.js), Procedural , Productivity, Unexpected/Unavoidable Risks (VISA ISSUES)

**Comment by kexuansong** [comment]
Acceptance test:
If the user tries to join channel by channel ID, then the channel appear on the user’s channel list and the user can see the messages in the group.

**Comment by jcdee01** [comment]
Work Breakdown:
Join Channels
---
- Create Users Class Backend (James) #32 

Develop User functions
--
Function: GETTERS and SETTERS
Function: Join Channel
Function: Read a .json file
Function: Write a .json file

**Comment by jcdee01** [comment]
**Test Case 6: Join Channel**
Type: System(UI) Test
Description: Join Channel-Positive
Prerequisite: Premade Valid Channel
Test Priority: High
Step 1: Navigate to site
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Valid Email and Password  
(Input: “email:test@hotmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 3: Join Channel Form
(Input: Click on “Join CHANNEL’, Expected Output: Join Channel Form, Actual Output: Join Channel Form, Test Result: Pass)
Step 4: Join channel with Valid Users
(Input: 321@gmail.com:123@gmail.com, Expected Output: Redirected to Channel and Channel Added in Dashboard, Actual Output: Redirected to Channel and Channel Added in Dashboard, Test Result: Pass)
FINAL RESULT: **PASS**

**Test Case 7: Join Channel**
Type: System(UI) Test
Description: Join Non-existent Channel
Prerequisite: Premade Valid Channel
Test Priority: High
Step 1: Navigate to site
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Valid Email and Password  
(Input: “email:test@hotmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 3: Join Channel Form
(Input: Click on “Join CHANNEL’, Expected Output: Join Channel Form, Actual Output: Join Channel Form, Test Result: Pass)
Step 4: Join invalid channel 
(Input: 321.com:123@gmail.com, Expected Output: Redirected to Dashboard, Actual Output: Redirected to Dashboard, Test Result: Pass)
FINAL RESULT: **PASS**
