### ISSUE TITLE
Implement Channel Creation Back-end

### ISSUE THREAD

**Issue by v2thegreat** [v2thegreat/SOEN-341-PRJKT#23]

**Comment by v2thegreat** [comment]
Issue under #11

**Comment by jcdee01** [comment]
Priority: HIGH
Risk: HIGH
Risks associated: Technical (webstrom, react, node.js), procedural, productivity issues, sudden growth in requirements

**Comment by jcdee01** [comment]
Breakdown:
Create Channel class
--
Develop Channel functions
Function: GETTERS and SETTERS
Function: Add users to a channel
Function: Read a .json file
Function: Write a .json file
