### ISSUE TITLE
Set Up Travis CI

### ISSUE THREAD

**Issue by WanProduction** [v2thegreat/SOEN-341-PRJKT#37]
Read About how to set up travis CI
Add a .travis.yml file to your forked repository
Push a build break into fork to see if travis finds it
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
https://docs.travis-ci.com/user/customizing-the-build/

**Comment by jcdee01** [comment]
Priority: LOW
RISK: LOW
Risk Associated: Productivity Issues, Technical
