### ISSUE TITLE
User story: Sign out

### ISSUE THREAD

**Issue by kexuansong** [v2thegreat/SOEN-341-PRJKT#41]
As a user, I want to be able to sign out of the system so that I can .protect my privacy.

**Comment by kexuansong** [comment]
Risk Assesment
---
Priority: Medium
Risk: Low
Risk Associated: Productivity, Procedural
Story point: 4

**Comment by kexuansong** [comment]
Acceptance test:
If user clicks the user profile icon, then the user profile window with user information pops out.

**Comment by jcdee01** [comment]
**Test Case 5: Signout**
Type: System(UI) Test
Description: Signout Case
Prerequisite: NA
Test Priority: Low
Step 1: Navigate to site 
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Valid Email and Password  
(Input: “email:test@hotmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 3: Sign Out
(Input: click on “sign Out”, Expected Output: Sign Out of Account and Redirect to Login page, Actual Output: Sign Out of Account and Redirect to Login page, Test Result: Pass)
FINAL RESULT: **PASS**

**Test Case 5: Add Channel**
Type: System(UI) Test
Description: Create a new text channel 
Prerequisite: 2 Premade Valid Account
Test Priority: High
Step 1: Navigate to site
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Valid Email and Password  
(Input: “email:test@hotmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 3: Add Channel
(Input: Click on “ADD CHANNEL’, Expected Output: Create Channel Form, Actual Output: Create Channel Form, Test Result: Pass)
Step 4: Submit Channel Form
(Input: “Channel name: ‘Test’, Friend’s Username: ‘test@gmail.com’ , message: “test””, Expected Output: Redirect to new channel test AND message: “Test” Displayed, Actual Output: Redirect to new channel test AND message: “Test” Displayed, Test Result: Pass)
FINAL RESULT: **PASS**

**Comment by jcdee01** [comment]
Successful Implemented #44
