### ISSUE TITLE
User story: Unread messages

### ISSUE THREAD

**Issue by kexuansong** [v2thegreat/SOEN-341-PRJKT#42]
As a user, I want to be notified when my channel is updated so I don't miss new posts.

**Comment by kexuansong** [comment]
Priority: Low
Risk: Medium
Risk Associated:  Technical, Procedural, Productivity
Story point: 4

**Comment by jcdee01** [comment]
Breakdown
Tagging Individuals
---
- Implement backend (James & Ali) 
- Merge Backend to Front End (Kate & Kelvin) #14 
     - makes sure tagged text is identifiable

**Comment by kexuansong** [comment]
### Acceptance test:
If there is an unread message, the user has a notification icon beside the channel.

**Comment by jcdee01** [comment]
**Test Case 8: Unread Messages**
Type: System(UI) Test
Description: Get an Unread Message Notification
Prerequisite: 2 Premade Valid Account
Test Priority: High
Step 1: Navigate to site
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Valid Email and Password  
(Input: “email:test@hotmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 3: Select "test" Channel
Step 4: Input message
(Input: type "unread message" in message box, Expected Output: message appears in channel view to user and channel notification sent to members(will be seen in later steps), Actual Results: message appears in channel view, Test Result: Pass)
Step 5: Login to reciever
(Input: “email:test@gmail.com; password: password”, Expected Output: Navigate to dashboard', Actual Output: Navigate to dashboard, Test Result: Pass)
Step 6: Inspect Channel View for notification
(Input: NA, Expected Output: notification appears(bell icon), Actual Output: notification appears, Test Result: Pass)
Final Result: **Pass**

**Comment by jcdee01** [comment]
Unread notification succesfully created
