### ISSUE TITLE
User story: User log in and sign up

### ISSUE THREAD

**Issue by WanProduction** [v2thegreat/SOEN-341-PRJKT#43]
As the user, I want to be able to sign-up to create my profile or log into my profile.

Priority: High
Risk: High
Risk Associated: Technical risks
Story point: 3

**Comment by jcdee01** [comment]
Breakdown:
Login and Signup
---
- Backend Authentification (Kelvin) #44 
-Create Frontend Interface for login(Kate) #39 
-Merge backend and front end (Kelvin)

**Comment by kexuansong** [comment]
### Acceptance test:
If the user tries to log in with the correct email and password, shows the channel page. If user tries to log in with incorrect email or password, warn the user. If user tries to make a new account, ask for email and password then create a new account.

**Comment by jcdee01** [comment]
**Test Case 1: Signup**
Type: System(UI) Test
Description: Signup-Positive Case
Prerequisite: NA
Test Priority: Medium
Step 1: Navigate to site 
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Prompt Signup Page
(Input: Click on “Register”, Expected Output: Navigate to Signup Page, Actual Output:Navigate to Signup Page, Test Result: Pass)
Step 3: Input Valid Email and Password
(Input: “email:test@hotmail.com, password: 1234567a, confirm password: 1234567a”, Expected Output: Navigate to Dashboard, Actual Output: Navigate to Dashboard, Test Result: Pass)
FINAL RESULT: **PASS**

**Test Case 2: Signup**
Type: System(UI) Test
Description: Signup-Negative Case
Prerequisite: Premade Account Made
Test Priority: Medium
Step 1: Navigate to site 
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Prompt Signup Page
(Input: Click on “Register”, Expected Output: Navigate to Signup Page, Actual Output:Navigate to Signup Page, Test Result: Pass)
Step 3: Input Invalid Email and Password
(Input: “email:test@hotmail.com, password: 1234567a, confirm password: 1234567a”, Expected Output: “Failed To add user”-prompt, Actual Output: “Failed To add user”-prompt, Test Result: Pass)
FINAL RESULT: **PASS**

**Test Case 3: Login**
Type: System(UI) Test
Description: Login-Positive Case
Prerequisite: Valid Account
Test Priority: Medium
Step 1: Navigate to site 
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input email and password  
(Input: test@hotmail.com,1234567a, Expected Output: Navigate to Dashboard, Actual Output: Navigate to dashboard, Test Result: Pass)
FINAL RESULT: **PASS**

**Test Case 4: Login**
Type: System(UI) Test
Description: Login-Negative Case
Prerequisite: NA
Test Priority: Medium
Step 1: Navigate to site 
(Input: localhost:3000/login, Expected Output: Login Page, Actual Output: Login Page, Test Result: PASS)
Step 2: Input Wrong Email and Password  
(Input: “email:asdf@gmail.com; password: password”, Expected Output:” Error logging in'', Actual Output: ” Error logging in”, Test Result: Pass)
Step 3: Input Valid Email but Wrong Password
(Input: “email:test@hotmail.com; password: password”, Expected Output:” ncorrect login Information'', Actual Output: ” Incorrect login Information”, Test Result: Pass)
FINAL RESULT: **PASS**

**Comment by jcdee01** [comment]
Authentification works well, issues resolved
